steps:
  - name: Setup environment
    run: |
      # Install shellcheck for linting bash scripts
      sudo apt-get update
      sudo apt-get install -y shellcheck
      
  - name: Verify setup
    run: |
      echo "Environment setup complete"
      shellcheck --version
